#!/bin/bash
if (($# < 3))
then 
echo "Parameters entered incorrect - use format [operation number number]"
echo "Operations: a - addition"
echo "            s - subtraction"
echo "            m - multiplication"
echo "            d - division"
exit 0
fi

add(){
value=$(($1 + $2))
echo $value
}

sub(){
value=$(($1 - $2))
echo $value
}

mult(){
value=$(($1 * $2))
echo $value
}

div(){
value=$(($1 / $2))
echo $value
}

case $1 in
"a") add "$2" "$3"
;;
"s") sub "$2" "$3"
;;
"m") mult "$2" "$3"
;;
"d") div "$2" "$3"
esac
